name: j99_mobile_manifest_flutter
description: Juragan99 Trans Manifest for Driver-Only.

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  indonesia: ^1.0.1
  cupertino_icons: ^1.0.2
  easy_splash_screen: ^1.0.3
  flutter_slidable: ^1.2.0
  blur: ^3.0.0
  mobile_scanner: ^1.0.0
  printing: ^5.7.4
  shimmer: ^2.0.0
  fluttertoast: ^8.0.9
  bluetooth_print: ^3.0.1
  http: ^0.13.4
  path_provider: ^2.0.9
  pdf_render: ^1.0.23
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.9.2
  flutter_speed_dial: ^5.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/j99-icon.png"